pipeline {
    agent any

    environment {
        REMOTE_HOST = 'ubuntu@37.9.53.243'
        SSH_KEY_ID = 'remote-ssh-key'  // ID ключа Jenkins с SSH приватным ключом
        REMOTE_APP_DIR = '/home/ubuntu/flask-api'  // Куда будет копироваться проект
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy via SSH') {
            steps {
                sshagent([SSH_KEY_ID]) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${REMOTE_HOST} '
                            rm -rf ${REMOTE_APP_DIR}
                        '
                        scp -r flask-api ${REMOTE_HOST}:${REMOTE_APP_DIR}
                        ssh ${REMOTE_HOST} '
                            cd ${REMOTE_APP_DIR}
                            docker-compose down || true
                            docker-compose up -d
                        '
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'Deployment finished.'
        }
    }
}
