pipeline {
    agent any

    environment {
        REMOTE_HOST = 'ubuntu@37.9.53.243'
        SSH_KEY_ID = 'remote-ssh-key'  // Jenkins credentials id для ssh private key
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Lint') {
            steps {
                sh 'pip install flake8'
                sh 'flake8 app'
            }
        }

        stage('Deploy') {
            steps {
                sshagent([env.SSH_KEY_ID]) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${env.REMOTE_HOST} '
                        cd /home/ubuntu/flask-api &&
                        docker-compose pull &&
                        docker-compose up -d
                    '
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished"
        }
    }
}
