version: '3.9'

services:
  postgres_db:
    image: postgres:16.1-alpine3.19
    container_name: postgres_db
    environment:
      POSTGRES_DB: USER_DB
      POSTGRES_USER: USER_DB
      POSTGRES_PASSWORD: PWD_DB
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U USER_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lesta_start_demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lesta_start_demo
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      API_PORT: 8887
      DB_URL: postgres://USER_DB:PWD_DB@postgres_db:5432/DB
    ports:
      - "8887:8887"

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_demo
    depends_on:
      - lesta_start_demo
    ports:
      - "8088:8088"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  postgres_data:
